### ISSUE TITLE
/phantom/pose Geomagic Touch values 

### ISSUE THREAD

**Issue by WoutKe** [bharatm11/Geomagic_Touch_ROS_Drivers#4]
[Hi @bharatm11 ,

While using the driver, I noticed that the x y z position of the Geomagic doesn't change when manipulating the stylus (seen on the topic /phantom/pose). They stay fixed at the values showed in the picture below (0; 0.035; -0.11).
This in contrast to the orientation parameters which are varying continuously.

In order to get the pose of the stylus in another way, I opt using a tf2 transformation on the joint states. But either they are getting the value of 0 at the waist, shoulder and elbow. I also added a screenshot of this below.

I tried figuring out why this is happening by going over the code, but could not find a solution. I mentioned an unknown calibration status when launching the ''omni_state.launch''. Could this be the problem?

Thank you in Advance.

![pose_GeomagicTouch](https://user-images.githubusercontent.com/98952544/157033580-76a6c0c7-34f9-4f03-b2e1-e3ec6c89ca85.png)
![JointStates](https://user-images.githubusercontent.com/98952544/157033574-f2d863a9-3c61-4c7f-aee7-4b4c85931996.png)
![launch GeomagicTouch](https://user-images.githubusercontent.com/98952544/157033579-0e82278b-f886-4368-b981-16a507a1b42a.png)

**Comment by bharatm11** [comment]
Hi @WoutKe,

I recommend trying out 2 things:

1. Try calibrating the haptic device using the Geomagic Touch Setup application. Refer: [https://github.com/bharatm11/Geomagic_Touch_ROS_Drivers/issues/2](https://github.com/bharatm11/Geomagic_Touch_ROS_Drivers/issues/2)
2. Try to read joint states through the _/phantom/joint_states_ topic

 All the best! :)

**Comment by RobinHeleven** [comment]
Thank you for your reply, but the device functions perfectly through the Setup and Diagnostics application. The problem seems to be related to omni_state in the code. While building we get a warning about the dependency target omni_state. 
![Dependency target of target omni_state does not exist](https://user-images.githubusercontent.com/101391580/157839103-fa167d64-f301-440b-ab3b-dc7e71acf9c3.png)

In the code editor errors pop up from line 225 where the omni_state_callback is first mentioned. 
![omni_state error](https://user-images.githubusercontent.com/101391580/157839437-db11fe68-def5-4af1-b68a-f72f0ac394c5.png)

Can we somehow install those depencencies manually? We did already fully reinstall the Openhaptics software and the Touch drivers with no luck.

**Comment by bharatm11** [comment]
Interesting. Based on @WoutKe's comment, I would think that this is not a build/dependency issue as it looks like you guys were able to build, run, and read some of the joint states.

Is there any chance that you are using a newer version of the Geomagic Touch that does things differently? Or maybe you're using a newer version of ROS...?

Do the installation instructions on the [original package from Francisco ](https://fsuarez6.github.io/projects/geomagic-touch-in-ros/) give any clues?

**Comment by WoutKe** [comment]
Meanwhile, this issue is solved. The problem was that our Ubuntu in terms of language differs from others which gave software malfuntions due to a difference of convention. By changing the language and reinstalling the drivers, the reading of the data of the Touch works perfectly.

**Comment by 159chenJie159** [comment]
hHi,

I am having the same issue. Have you found a solution? I don't know how to change the language.

Thank you
